# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [27]:
# import libraries
import pandas as pd
import numpy as np
import re

#### Import data set.

Import data set `Pokemon` from Ironhack's database. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [53]:
# import data set from Ironhack's database
pokemon=pd.read_csv('C:\\Users\\admin\\Documents\\Ironhack_lessons\\Module 1\\Pokemon.csv')

#### Print first 10 rows of `pokemon`.

In [4]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [54]:
# your code here
type1=pokemon['Type 1'].unique()
type2=pokemon['Type 2'].unique()
list=set(np.concatenate((type1, type2), axis=0))
list
#another way
set(pokemon['Type 1'].unique()).union(set(pokemon['Type 1'].unique()))

{'Bug',
 'Dark',
 'Dragon',
 'Electric',
 'Fairy',
 'Fighting',
 'Fire',
 'Flying',
 'Ghost',
 'Grass',
 'Ground',
 'Ice',
 'Normal',
 'Poison',
 'Psychic',
 'Rock',
 'Steel',
 'Water',
 nan}

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [55]:
# your code here
pokemon['Name']=["".join(re.findall(r'Mega\s\w+',x)) if ('Mega') in x  else x for x in pokemon.Name ]
pokemon['Name'].apply(lambda x: ''.join(re.findall(r'Mega\s\w+',x)) if ('Mega') in x  else x for x in pokemon.Name)

# test transformed data
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [58]:
# your code here
pokemon['A/D']=pokemon.eval('Attack/Defense').round(2)
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.67
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.45
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.83
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.67
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.92

#### Identify the pokemon with the highest `A/D Ratio`.

In [77]:
# your code here
pokemon.sort_values('A/D', ascending=False).head(1)

#autre methode
pokemon.loc[pokemon['A/D'].idxmax()]

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
A/D                            9
Combo_Type               Psychic
Name: 429, dtype: object

#### Identify the pokemon with the lowest A/D Ratio.

In [76]:
# your code here
pokemon.sort_values('A/D', ascending=True).head(1)
#autre methode
pokemon.loc[pokemon['A/D'].idxmin()]

#                  213
Name           Shuckle
Type 1             Bug
Type 2            Rock
Total              505
HP                  20
Attack              10
Defense            230
Sp. Atk             10
Sp. Def            230
Speed                5
Generation           2
Legendary        False
A/D               0.04
Combo_Type    Bug-Rock
Name: 230, dtype: object

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [81]:
# your code here
pokemon['Type 2']=pokemon['Type 2'].fillna('')
pokemon['Type 1']=pokemon['Type 1'].fillna('')
pokemon['Combo_Type']= (pokemon['Type 1']+'-'+pokemon['Type 2']).str.strip('-') 
pokemon
#another way to avoid Grass-Poison and Poison-Grass is to create tupple 
pokemon['Combo Type']=pokemon.apply(lambda x: (x['Type 1'],x['Type 2']) if (x['Type 2']!='') &(x['Type 1']<x['Type 2']) else ((x['Type 2'],x['Type 1']) ),  axis=1)
pokemon['Combo Type']=pokemon['Combo Type'].apply(lambda x: '-'.join(x).strip('-'))
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D,Combo_Type,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.00,Grass-Poison,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.98,Grass-Poison,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.99,Grass-Poison,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.81,Grass-Poison,Grass-Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.21,Fire,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.67,Rock-Fairy,Fairy-Rock
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.45,Rock-Fairy,Fairy-Rock
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.83,Psychic-Ghost,Ghost-Psychic
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.67,Psychic-Dark,Dark-Psychic
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.92,Fire-Water,Fire-Water

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [ ]:
# your code here

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [ ]:
# your code here

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [ ]:
# your code here